/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Zeus",
	author = "Jessecar96 & Dr. Cat, MD",
	description = "This is a gamemode",
	version = "1.0",
	url = "jessecar96.net"
}

public OnPluginStart()
{
	//Something goes here
}
